# Generated by Django 5.0.1 on 2024-02-13 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('valid_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='paymentdate',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subscription'),
        ),
    ]
